### ISSUE TITLE
Add home button on game pages

### ISSUE THREAD

**Issue by juliasophieg** [juliasophieg/CountryPedia-2.0#10]
### Add Home button on game pages 🏠

Currently, there’s no home button available on the game pages, making it difficult for users to navigate back to the main menu. 
The placement and styling are optional but should match the current style of the page.

<div>
    <img width="50%" alt="Screenshot 1" src="https://github.com/user-attachments/assets/144c84e6-c2bd-48fc-b8d0-9e7efc8a580e">
    <img width="50%" alt="Screenshot 2" src="https://github.com/user-attachments/assets/360d8371-d593-4a30-a64a-89595212664d">
</div>

**Comment by vsnikhilvs** [comment]
Could you please assign me this? @juliasophieg

**Comment by snehautekar05** [comment]
Hi @juliasophieg ,can you assign this issue to me?

**Comment by juliasophieg** [comment]
Sure @snehautekar05 !

**Comment by Mayuresh1134** [comment]
I have made the changes and sent a pull request
