### ISSUE TITLE
Add counter for correct guesses in flag game

### ISSUE THREAD

**Issue by juliasophieg** [juliasophieg/CountryPedia-2.0#9]
### Add a Counter for Right Guesses
Currently, there's no count to indicate how many right guesses the user has made. The placement and styling are optional but should match the current style of the page.

<img width="1277" alt="Flag game screenshot" src="https://github.com/user-attachments/assets/1845c6b2-8966-4c45-8522-1003730f2c5e">

**Comment by snehautekar05** [comment]
Hi @juliasophieg ,Can you asssign this issue to me?

**Comment by juliasophieg** [comment]
You are assigned @snehautekar05
